-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 18:00:23 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_matcha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_matcha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_matcha` DEFAULT CHARACTER SET utf8 ;
USE `db_matcha` ;

-- -----------------------------------------------------
-- Table `db_matcha`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_matcha`.`Users` (
  `UserId` INT(11) NOT NULL AUTO_INCREMENT,
  `UserToken` VARCHAR(255) NOT NULL,
  `Login` VARCHAR(45) NULL DEFAULT '',
  `Password` VARCHAR(45) NULL DEFAULT '',
  `FirstName` VARCHAR(45) NULL DEFAULT '',
  `LastName` VARCHAR(45) NULL DEFAULT '',
  `Age` INT(11) NULL DEFAULT '0',
  `Mail` VARCHAR(45) NULL DEFAULT '',
  `Gender` VARCHAR(45) NULL DEFAULT '' COMMENT 'M:Male\nF:Female\nA:Ambiguous',
  `Orientation` VARCHAR(45) NULL DEFAULT 'Hetero' COMMENT 'Hetero\nBi\nHomo',
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
